In [2]:
from xgboost_utils import *

<h1>XGBoost</h1>

In [3]:
X_train, y_train, X_val, y_val = prep_data_for_xgboost()
X_train.head()

Shape of training data:  (48000, 20)
Shape of training label:  (48000, 1)
Shape of validation data:  (12000, 20)
Shape of validation label:  (12000, 1)

,rent_approval_date,flat_type,flat_model,floor_area_sqm,lease_commence_date,latitude,longitude,mrts_within_3km,nearest_distance_to_mrt,pri_schs_within_6km,gep_schs_within_5km,malls_within_3km,nearest_distance_to_gep,nearest_distance_to_mall,highest_pos_corr,region_central region,region_east region,region_north region,region_north-east region,region_west region
0,2107,3,2365.067275,67.0,1979,1.366600,103.855579,11,764.670207,52,2,11,1850.376297,1034.851528,10.227563,0.0,0.0,0.0,1.0,0.0
1,2201,5,2640.896729,110.0,2003,1.401158,103.751472,4,607.646696,25,0,11,9125.370545,597.191138,11.105234,0.0,0.0,0.0,0.0,1.0
2,2107,3,2365.067275,67.0,1978,1.316994,103.768507,8,423.362498,21,4,9,860.187654,247.035245,10.227563,0.0,0.0,0.0,0.0,1.0
3,2103,3,2614.410973,74.0,1984,1.347162,103.742808,6,775.808574,39,1,7,3701.476616,787.588358,10.104055,0.0,0.0,0.0,0.0,1.0
4,2206,4,2614.410973,93.0,2002,1.450165,103.819307,4,156.306323,27,0,5,10555.854553,218.614539,11.564181,0.0,0.0,1.0,0.0,0.0

In [4]:
xgb_model = xgb.XGBRegressor(
            n_estimators=1800, max_depth=5, eta=0.01, subsample=0.7, colsample_bytree=0.7,
            objective="reg:squarederror"
        )
# xgb_model.fit(X_train, y_train, 
#             eval_set=[(X_train, y_train), (X_val, y_val)])
xgb_model.fit(X_train, y_train)
y_val_pred = xgb_model.predict(X_val)
print('Validation loss:', np.sqrt(mean_squared_error(y_val, y_val_pred)))
y_train_pred = xgb_model.predict(X_train)
print('Training loss:', np.sqrt(mean_squared_error(y_train, y_train_pred)))

Validation loss: 481.4906954982108
Training loss: 457.6630179309819

<h1>Gradient Boosting</h1>

In [16]:
X_train, y_train, X_val, y_val = prep_data_for_xgboost()
X_train.head()

Shape of training data:  (48000, 20)
Shape of training label:  (48000, 1)
Shape of validation data:  (12000, 20)
Shape of validation label:  (12000, 1)

,rent_approval_date,flat_type,flat_model,floor_area_sqm,lease_commence_date,latitude,longitude,mrts_within_3km,nearest_distance_to_mrt,pri_schs_within_6km,gep_schs_within_5km,malls_within_3km,nearest_distance_to_gep,nearest_distance_to_mall,highest_pos_corr,region_central region,region_east region,region_north region,region_north-east region,region_west region
0,2107,3,2365.067275,67.0,1979,1.366600,103.855579,11,764.670207,52,2,11,1850.376297,1034.851528,10.227563,0.0,0.0,0.0,1.0,0.0
1,2201,5,2640.896729,110.0,2003,1.401158,103.751472,4,607.646696,25,0,11,9125.370545,597.191138,11.105234,0.0,0.0,0.0,0.0,1.0
2,2107,3,2365.067275,67.0,1978,1.316994,103.768507,8,423.362498,21,4,9,860.187654,247.035245,10.227563,0.0,0.0,0.0,0.0,1.0
3,2103,3,2614.410973,74.0,1984,1.347162,103.742808,6,775.808574,39,1,7,3701.476616,787.588358,10.104055,0.0,0.0,0.0,0.0,1.0
4,2206,4,2614.410973,93.0,2002,1.450165,103.819307,4,156.306323,27,0,5,10555.854553,218.614539,11.564181,0.0,0.0,1.0,0.0,0.0

In [17]:
from sklearn.ensemble import GradientBoostingRegressor
gb_model = GradientBoostingRegressor(
            n_estimators=200, learning_rate=0.1, min_samples_split=500,min_samples_leaf=60,max_depth=8,max_features='sqrt',subsample=0.8,random_state=10
        )

gb_model.fit(X_train, y_train)
y_val_pred = gb_model.predict(X_val)
print('Validation loss:', np.sqrt(mean_squared_error(y_val, y_val_pred)))
y_train_pred = gb_model.predict(X_train)
print('Training loss:', np.sqrt(mean_squared_error(y_train, y_train_pred)))

/opt/homebrew/lib/python3.11/site-packages/sklearn/ensemble/_gb.py:424: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Validation loss: 482.57352582549424
Training loss: 456.47080437744125

<h1>Random Forest</h1>

In [18]:
X_train, y_train, X_val, y_val = prep_data_for_xgboost()
X_train.head()

Shape of training data:  (48000, 20)
Shape of training label:  (48000, 1)
Shape of validation data:  (12000, 20)
Shape of validation label:  (12000, 1)

,rent_approval_date,flat_type,flat_model,floor_area_sqm,lease_commence_date,latitude,longitude,mrts_within_3km,nearest_distance_to_mrt,pri_schs_within_6km,gep_schs_within_5km,malls_within_3km,nearest_distance_to_gep,nearest_distance_to_mall,highest_pos_corr,region_central region,region_east region,region_north region,region_north-east region,region_west region
0,2107,3,2365.067275,67.0,1979,1.366600,103.855579,11,764.670207,52,2,11,1850.376297,1034.851528,10.227563,0.0,0.0,0.0,1.0,0.0
1,2201,5,2640.896729,110.0,2003,1.401158,103.751472,4,607.646696,25,0,11,9125.370545,597.191138,11.105234,0.0,0.0,0.0,0.0,1.0
2,2107,3,2365.067275,67.0,1978,1.316994,103.768507,8,423.362498,21,4,9,860.187654,247.035245,10.227563,0.0,0.0,0.0,0.0,1.0
3,2103,3,2614.410973,74.0,1984,1.347162,103.742808,6,775.808574,39,1,7,3701.476616,787.588358,10.104055,0.0,0.0,0.0,0.0,1.0
4,2206,4,2614.410973,93.0,2002,1.450165,103.819307,4,156.306323,27,0,5,10555.854553,218.614539,11.564181,0.0,0.0,1.0,0.0,0.0

In [19]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 50, stop = 200, num = 4)]
# Number of features to consider at every split
max_features = ['sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(6, 10, num = 5)]

# Minimum number of samples required to split a node
min_samples_split = [450, 500, 550]
# Minimum number of samples required at each leaf node
min_samples_leaf = [40, 50, 60]
# Method of selecting samples for training each tree
bootstrap = [True]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
print(random_grid)

{'n_estimators': [50, 100, 150, 200], 'max_features': ['sqrt'], 'max_depth': [6, 7, 8, 9, 10], 'min_samples_split': [450, 500, 550], 'min_samples_leaf': [40, 50, 60], 'bootstrap': [True]}

In [ ]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestRegressor()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(X_train, y_train)

In [ ]:
rf_random.best_params_

In [20]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100, min_samples_split=450, min_samples_leaf=40, max_features='sqrt', max_depth=10, bootstrap=True)
model.fit(X_train, y_train)
y_val_pred = model.predict(X_val)
print('Validation loss:', np.sqrt(mean_squared_error(y_val, y_val_pred)))
y_train_pred = model.predict(X_train)
print('Training loss:', np.sqrt(mean_squared_error(y_train, y_train_pred)))

/opt/homebrew/lib/python3.11/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Validation loss: 494.5226158575061
Training loss: 492.6628199302422